branches:
  only:
  - master
  - development
sudo: false
git:
  quiet: true
addons:
  apt:
    packages:
      - autoconf
      - automake
      - libtool
      - pkg-config
      - curl
      - git
      - cmake
      - gcc
      - gperf
      - texinfo
      - yasm
      - nasm
      - bison
      - autogen
      - patch
  homebrew:
    packages:
      - nasm
    update: true
matrix:
  include:
    - name: "Android Main Build"
      language: android
      dist : trusty
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-24
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "cmake;3.10.2.4988404"
        - echo y | sdkmanager "lldb;3.1"
      before_install:
        - touch $HOME/.android/repositories.cfg
      before_script:
        - export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./android.sh --no-output-redirection
    - name: "Android LTS Build"
      language: android
      dist : trusty
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-16
          - android-21
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "cmake;3.10.2.4988404"
        - echo y | sdkmanager "lldb;3.1"
      before_install:
        - touch $HOME/.android/repositories.cfg
      before_script:
        - export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./android.sh --lts --no-output-redirection
    - name: "iOS Main Build"
      language: objective-c
      osx_image: xcode10.2
      before_script:
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./ios.sh --no-output-redirection
    - name: "iOS LTS Build"
      language: objective-c
      osx_image: xcode7.3
      before_script:
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./ios.sh --lts --no-output-redirection
    - name: "tvOS Main Build"
      language: objective-c
      osx_image: xcode10.2
      before_script:
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./tvos.sh --no-output-redirection
    - name: "tvOS LTS Build"
      language: objective-c
      osx_image: xcode7.3
      before_script:
        - rm -f ./build.log
      after_success:
        - grep -e INFO ./build.log | grep build
      after_failure:
        - tail -30 ./build.log
        - tail -30 ./src/ffmpeg/ffbuild/config.log
      script:
        - bash ./tvos.sh --lts --no-output-redirection